services:
  economoose-nodejs:
    container_name: economoose-nodejs
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    restart: unless-stopped
    ports:
      - "3123:80"
    depends_on:
      - economoose-mongo
  economoose-mongo:
    container_name: economoose-mongo
    image: mongo:4
    command: mongod --port 27017 --bind_ip 0.0.0.0
    restart: unless-stopped
    volumes:
      - /data/db/economoose_mongo:/data/db
    expose:
      - "27017"
