version: "3"
services:
  nodejs:
    container_name: nodejs
    build:
        context: ./
        dockerfile: ./docker/web/Dockerfile
    restart: unless-stopped
    ports:
      - "3123:3123"
    depends_on:
      - mongo
#  mongo:
#    container_name: mongo
#    image: mongo
#    command: mongod --port 27018
#    restart: unless-stopped
#    volumes:
#      - ./mongo:/data/db
#    ports:
#      - '27018:27018'
  mongo:
    container_name: mongo
    build:
        context: ./
        dockerfile: ./docker/db/Dockerfile
    command: mongod --port 27018 --bind_ip_all
    restart: unless-stopped
    volumes:
      - ./mongo2:/data/db
    ports:
      - '27018:27018'

